apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: thehive
  namespace: thehive
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: thehive
      app.kubernetes.io/component: soar
