apiVersion: v1
kind: ServiceAccount
metadata:
  name: thehive
  namespace: thehive
  annotations:
    iam.gke.io/gcp-service-account: thehive-workload@thehive-soar-lab-12345.iam.gserviceaccount.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thehive
  namespace: thehive
spec:
  template:
    spec:
      volumes:
        - name: config
          configMap:
            name: thehive-config
        - name: attachments
          csi:
            driver: gcsfuse.csi.storage.gke.io
            readOnly: false
            volumeAttributes:
              bucketName: REPLACE_WITH_PROJECT_ID-thehive-attachments
              mountOptions: "implicit-dirs"
