apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thehive
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: security-platform
  source:
    repoURL: "https://github.com/Ayush2411/hive-clone.git"
    targetRevision: main
    path: k8s/overlays/gcp-free-tier
  destination:
    server: https://kubernetes.default.svc
    namespace: thehive
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
