apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - thehive/serviceaccount.yaml
  - thehive/configmap.yaml
  - thehive/deployment.yaml
  - thehive/service.yaml
  - thehive/ingress.yaml
  - thehive/pdb.yaml
  - thehive/networkpolicy.yaml
  - cassandra/service.yaml
  - cassandra/statefulset.yaml
  - cassandra/pdb.yaml
  - cassandra/networkpolicy.yaml
  - elasticsearch/service.yaml
  - elasticsearch/statefulset.yaml
  - elasticsearch/pdb.yaml
  - elasticsearch/networkpolicy.yaml
